multiformats/js-cid

- .travis.yml
- README.md
- package.json
- test/index.spec.js
Ref https://github.com/ipfs/js-ipfs/pull/485
> Async Crypto Endeavour

- src/index.js
- test/index.spec.js
Me and @gozala went through details of CID design, v0 vs v1, what does each piece mean and we came with a lot more clarity from that discussion, you can find the log here:
https://botbot.me/freenode/ipfs/2017-01-21/?msg=79711046&page=1
To avoid further confusion, I changed the behaviour of a CIDv0.toBaseEncodedString to only allow base58, throwing an error that informs the user they need to migrate to v1. Added a test for this
> fix: throw an error if another base is picked for cidv0

- test/index.spec.js
Added two more test cases for CID.buffer, for both versions 0 and 1.
(Cf. Issue $46.)
> Added test cases for cid.buffer

- package.json
- src/index.js
- test/index.spec.js
Use `getCodeVarint()` instead of directly accessing the lookup
table of the multicodec module. This leads to nicer error messages
if the given codec is not found.
Prior to this commit:
buffer.js:183
throw new TypeError(kFromErrorMsg);
^
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
at Function.Buffer.from (buffer.js:183:11)
at CID.get buffer [as buffer] (/home/vmx/src/pl/js-cid/src/index.js:123:18)
at CID.toBaseEncodedString (/home/vmx/src/pl/js-cid/src/index.js:184:44)
at Object.<anonymous> (/home/vmx/src/pl/js-cid/keccak.js:16:19)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)
at …
> Remove direct access to codec lookup table

- src/index.js
- test/index.spec.js
This makes stringifying a CID super easy like `${cid}` or `cid+''`.
resolves #54
> feat: add toString function

- README.md
I end up referring to these docs often and the generated documentation is not very useful or informative.
I wrote up more human readable docs and put them in the README to replace the generated docs. This API isn't so large that we can't just document it in the README.
> docs: move API docs into README

- src/index.js
- test/index.spec.js
The `toV0` and `toV1` functions were returning instances of the unwrapped CID class not the wrapped one with the class-is smarts.
> fix: toV0 and toV1 create instances that cause isCID be false

- README.md
There was a type `isCid()` -> `isCID()`.
> docs: function is called `isCID()`

- package.json
Git hooks are now handled directly by aegir (with git-validate).
Hence the pre-commit package is no longer needed.
> chore: remove pre-commit package

- src/index.js
- test/index.spec.js
I quickly threw this together in response to https://github.com/ipfs/js-ipfs/issues/1788.
Right now, when attempting to get content not in the local repo, `cid.buffer` will be requested multiple times. See:
https://github.com/ipfs/js-ipfs-repo/blob/01a47375f5a07c5b9b3312c1674923a3c2854ae8/src/blockstore.js#L163-L171
`cidToDsKey` accesses `cid.buffer` and will be called twice in this one method (and possibly other times throughout the code base) so in this case it is worth the overhead of caching the buffer because recreating it is expensive.
resolves https://github.com/ipfs/js-ipfs/issues/1788
> perf: cache buffer form of CID when created

- src/cid-util.js
- src/index.js
- test/index.spec.js
BREAKING CHANGE - previously base was not preserved and all CIDs would
be normalised to base58btc when asked for their string representation.
The default will change to base32 in https://github.com/multiformats/js-cid/pull/73/files
The idea behind this change is that we shouldnt lose information when
the user passes us a base encoded string, but keep it and use it as
the default base so toString returns the same string they provided.
I'd like this as a fix for ipld explorer, which currently forces all
CIDs into base58btc, seee: https://github.com/ipfs-shipyard/ipfs-webui/issues/999
This PR is the smallest change I can see to make it work. Do we want
to also add base as a constructor parameter? If so, i guess it should
go at the end as it's optional, but thats aesthetically displeasing
as …
> feat: preserve base when constructed from a string

- .flowconfig
- src/index.js.flow
Add flow type definitions which would improve workflow for dependent libraries that happen to use flow type-checker.
This just `index.js.flow` is what flow would resolve to when imported module resolves to `index.js` and there for dependencies of this library will be able to infer type info.
> feat: add flow typedefs

- README.md
- Clarify how to use the mutlibaseName param in the README.
- Update the usage section with clear examples
> docs: add multibaseName param with better examples

- src/index.js.flow
Add 4th optional parameter introduced by #77
> fix: update typedefs to reflect API changes

- README.md
- src/index.js
- test/index.spec.js
This switches the default encoding for v1 CIDs from base58btc to base32. See https://github.com/ipfs/js-ipfs/issues/1995 for details.
BREAKING CHANGE: The default string encoding for v1 CIDs has changed from base58btc to base32.
> refactor: default to base32 encoding for v1 CIDs

- src/index.js
- test/index.spec.js
When creating a CID from another CID instance that was created by and old version of this module (< 0.7) the `multibaseName` property would become `undefined` and cause an error to be thrown when calling `toString`. This PR ensures an appropriate `multibaseName` is picked in the edge case that this happens.
> fix: throw on toString when create new CID from old CID

- package.json
- src/index.d.ts
Offering to submit and maintain these types. Given the relative stability of js-cids, this seems like a low maintenance PR.
> Add typescript types

- src/index.js
Fixes #96
this is good practice anyway
> fix: explicitly require .json ext of base-table

- src/index.d.ts
Using the `default` export is for ES2015 modules, which is fine for typescript etc, but the `export=` style is technically more correct for this module. Also adds docs and removes extraneous namespace in favor of explicit types.
> fix: more correct type defs + docs

- package.json
- test/index.spec.js
> Part of https://github.com/ipfs/go-ipfs/issues/7318
This PR:
- adds support for Base36
- adds test for ED25519 libp2p key represented as CIDv1 in Base36
@vmx the goal here is fix cid.ipfs.io (https://github.com/multiformats/cid-utils-website/issues/23) before go-ifps 0.6 is released. Are you able to merge this and release new version of `cids` to NPM?
> feat: support Base36

- package.json
- test/index.spec.js
Fixes #92 exception being throw by CID constructor when identity multihash is used
> fix: support for identity multihash

- README.md
- package.json
- src/cid-util.js
- src/index.d.ts
- src/index.js
- src/index.js.flow
- test/cid-util.spec.js
- test/helpers/gen-cid.js
- test/index.spec.js
- test/profiling/cidperf-x.js
Relaxes input from requiring node `Buffer`s to being `Uint8Arrays`.
This also means that the `.buffer` (now `.byte`) and `.prefix` properties have changed to be `Uint8Array`s.
Depends on:
BREAKING CHANGES:
- node `Buffer`s have been replaced with `Uint8Array`s
- the `.buffer` property has been renamed to `.bytes` and is now a `Uint8Array`
- the `.prefix` property is now a `Uint8Array`
> fix: replace node buffers with uint8arrays

- README.md
- src/index.d.ts
- src/index.js
- src/index.js.flow
- test/index.spec.js
(this PR assumes #117, review should focus only on the HEAD commit please, c043bc5)
Ref: https://github.com/multiformats/js-cid/pull/117#issuecomment-668131658
The idea here is that js-multiformats is going to require a switch to using the multicodec integer code rather than string, which does away with the need to bundle the entire multicodec table (and if you want string and you're happy to have the table then that's fine but you get to choose that). Experience shows that this is the most painful compatibility problem when switching between this library and `multiformats.CID` (and vice versa). Having a constructor that can take (optionally) an integer code rather than a string makes it the same constructor as `multiformats.CID` and exposing the `code` property makes it the same …
> feat: expose codec code and allow construction by code

- package.json
With updating the dependencies, we now never return Node.js Buffers
There were cases where CIDs where returned as Node.js Buffers. Now all
CIDs are returned as Uint8Array only.
Fixes #126.
> fix: never return Node.js Buffers

- package.json
- src/index.js
- test/index.spec.js
The changes in #131 broke the tests of IPFS and probably quite a few other modules.
This sort of thing used to work, now does not:
```js
expect(ipfs.bitswap.unwant.calledWith(new CID(cidStr), defaultOptions)).to.be.true()
```
The reason it breaks is because internally `calledWith` does a `deepEqual` on the args which compares (among other things) the properties of the passed objects.
We used to use `Object.defineProperty` to create cached versions of expensive to calculate fields which makes fields non-enumerable by default so they are skipped during the `deepEqual` check.
Now we just set the fields on the object which means instances have different fields depending on which constructor branch was hit or worse, if the instances properties have been accessed.
> fix: allow CIDs to be compared through deep equality

- src/index.js
This fixes regression caused by switch to generated typedefs which turned `isCID` to non type guard predicate.
For details on type guards see: https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards
> fix: turn isCID to a type guard

- package.json
- src/index.js
Using internal modules is a bad idea, but this is a quick fix in order
to not break the world.
> fix: use latest multicodec release

- package.json
Fixes regression introduced by #131 due to incorrect type mappings.
P.S.: It was not caught by js-ipfs because import end up having `any` type
> fix: typing mappings

- src/index.js
- test/index.spec.js
Added types in multicodec introduces issue in js-ipfs [when using `multicodec.getName(cid.code)`](https://github.com/ipfs/js-ipfs/blob/eceb0d4fc313f8b8c763f508c0fab25eaa91c10a/packages/ipfs-http-client/src/dag/put.js#L31) because `cid.code` was entyped as number while `getName` expects `CodecNumber` that is subset of number.
This change addresses that issue by changing `code` type accordingly & updating `codec` type to also fix  `multicodec.getNumber(cid.codec)`.
I also have noticed that generated types had bunch fields `version`, `codec` and `multihash` types generated as `any`, that is because constructor has early returns so type annotations at the end of the constructor were ignored. This pull fixes that by moving those annotations at the top of the file instead.
> fix: types to align with multicodec api

- package.json
- src/index.js
- test/cid-util.spec.js
- test/helpers/gen-cid.js
- test/index.spec.js
- test/profiling/cidperf-x.js
This PR updates aegir and fixes errors with the new ts config and removes typesVersions.
`typesVersions` workaround makes TS rewrite imports to `cids` to `cids/src` and because this package doesn't really needs this a workaround its just removed.
This should fix https://github.com/libp2p/js-libp2p/issues/839#issuecomment-756407072
> fix: fix types and remove typesVersions
